/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-10-28 07:48:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.cgiKmall;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import a.b.c.com.cgi.kmall.CartVO;
import java.util.ArrayList;
import java.text.DecimalFormat;

public final class cartView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("a.b.c.com.cgi.kmall.CartVO");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>CART VIEW</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	function findPay(){\r\n");
      out.write("		alert(\"결제 API 아임포트(import) 사용하기 \");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function findClear(){\r\n");
      out.write("		location.href=\"/springHbe/cgiKmall/cartClear.jsp\"\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function findGo(){\r\n");
      out.write("		location.href=\"/springHbe/cgiKmall/kosmoMall.jsp\"\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 request.setCharacterEncoding("EUC-KR"); 
      out.write('\r');
      out.write('\n');

	ArrayList<CartVO> cart = null;	
	Object obj = session.getAttribute("cart");	//세션 객체에서 cart 값을 가져온다.
	
	if(obj == null) {	//세션 정보가 없으면 배열을 생성 : 주문한 제품이 없다
		cart = new ArrayList<CartVO>();	
	} else {			//세션 정보가 있으면 강제로 캐스팅 : 주문한 제품이 있다
		cart = (ArrayList<CartVO>) obj;
	}

      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<h3>[ 장바구니 보기 ]</h3>\r\n");
      out.write("<hr>\r\n");
      out.write("<table border=\"1\">\r\n");
      out.write("<tr align=\"center\">\r\n");
      out.write("	<td>번호</td>\r\n");
      out.write("	<td>과일명</td>\r\n");
      out.write("	<td>단가</td>\r\n");
      out.write("	<td>주문 수량</td>\r\n");
      out.write("	<td>가격</td>\r\n");
      out.write("</tr>\r\n");

	if (cart.size() == 0){

      out.write("\r\n");
      out.write("<tr align=\"center\">\r\n");
      out.write("<td colspan=\"5\">\r\n");
      out.write("	장바구니에 담기 상품이 없습니다\r\n");
      out.write("	<a href=\"/springHbe/cgiKmall/kosmoMall.jsp\">주문하기</a>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
 		
	}else{
		int totalSum = 0;
		int total = 0;
		DecimalFormat df = new DecimalFormat("￦#,##0");
		for (int i=0; i < cart.size(); i++){
			CartVO cvo = cart.get(i);

      out.write("\r\n");
      out.write("			<tr align=\"center\">\r\n");
      out.write("				<td>");
      out.print( i + 1 );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( cvo.getName() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( df.format(cvo.getPrice()) );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( cvo.getCnt() );
      out.write("</td>\r\n");
      out.write("				");
 total = cvo.getPrice() * cvo.getCnt(); 
      out.write("\r\n");
      out.write("				<td>");
      out.print( df.format(total) );
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");
 totalSum += total; 
      out.write('\r');
      out.write('\n');
			
		}

      out.write("\r\n");
      out.write("		<tr align=\"center\">\r\n");
      out.write("			<td colspan=\"4\">\r\n");
      out.write("			<input type=\"button\" value=\"결제하기\" onclick=\"findPay()\" />\r\n");
      out.write("			<input type=\"button\" value=\"장바구니 비우기\" onclick=\"findClear()\" />\r\n");
      out.write("			<input type=\"button\" value=\"쇼핑 계속하기\" onclick=\"findGo()\" />\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>");
      out.print( df.format(totalSum) );
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
		
	}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
